"""detect models

Revision ID: c5e6cb4f36d2
Revises: 
Create Date: 2025-06-02 10:37:42.304288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e6cb4f36d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('song', sa.String(), nullable=False),
    sa.Column('participants', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('absentees', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('song', sa.String(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('available_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person_availability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_time')
    op.drop_table('song_session')
    op.drop_table('session_weight')
    op.drop_table('schedule_participant')
    op.drop_table('person_availability')
    op.drop_table('base_schedule')
    op.drop_table('admin_page')
    # ### end Alembic commands ###
